#!/bin/bash
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=visitorCount\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=engagementTime\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=pageviews\&siteId=2
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=visitorCount\&siteId=2
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=engagementTime\&siteId=2
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=pageviews\&siteId=3
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=visitorCount\&siteId=3
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=engagementTime\&siteId=3
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=pageviews\&siteId=4
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=visitorCount\&siteId=4
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=engagementTime\&siteId=4
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=pageviews\&siteId=5
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=visitorCount\&siteId=5
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=engagementTime\&siteId=5
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=pageviews\&siteId=6
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=visitorCount\&siteId=6
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=engagementTime\&siteId=6


curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=1\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=1\&filter=pageviews\&siteId=2
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=1\&filter=pageviews\&siteId=3
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=1\&filter=pageviews\&siteId=4
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=1\&filter=pageviews\&siteId=5
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=1\&filter=pageviews\&siteId=6
curl http://localhost:8080/publisherv1/report/v1/sessionfrequency?dateRange=1\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/sessionrecency?dateRange=1\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/sessiondepth?dateRange=1\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/sessionduration?dateRange=1\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/audience_segment?Aggregateby=subcategory\&dateRange=1\&filter=engagementTime\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/audience_segment?Aggregateby=subcategory\&dateRange=1\&filter=visitorCount\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=1\&filter=visitorCount\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=4\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=4\&filter=visitorCount\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/visitorType?dateRange=1\&filter=engagementTime\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=4\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/sessionfrequency?dateRange=4\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/sessionrecency?dateRange=4\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/sessiondepth?dateRange=4\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/sessionduration?dateRange=4\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/audience_segment?Aggregateby=subcategory\&dateRange=4\&filter=engagementTime\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/audience_segment?Aggregateby=subcategory\&dateRange=4\&filter=visitorCount\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=4\&filter=visitorCount\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=6\&filter=pageviews\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/audience_segment?Aggregateby=subcategory\&dateRange=6\&filter=engagementTime\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/audience_segment?Aggregateby=subcategory\&dateRange=6\&filter=visitorCount\&siteId=1
curl http://localhost:8080/publisherv1/report/v1/refcurrentoriginal?dateRange=6\&filter=visitorCount\&siteId=1
